### ISSUE TITLE
oom in error recovery of parser when parsing `(;`

### ISSUE THREAD

**Issue by lenawanel** [capy-language/capy#2]
on parsing a source file containing only `(;` the parser OOMs in the `Parser::error_with_recovery_set_no_default()` method

**Comment by lenawanel** [comment]
it's caused by this loop
https://github.com/capy-language/capy/blob/c90d40e21119e75a67693a0976561e2cab4c1a70/crates/parser/src/grammar/expr.rs#L336

never calling bump, and continuing to push new events and errors.

**Comment by lenawanel** [comment]
this also happens with just  `}`   a very quick fix for all those is to set `parser::DEFAULT_RECOVERY_SET` to `TokenSet::NONE`

**Comment by NotAFlyingGoose** [comment]
oof, you're right. I found another one along similar lines. I'm gonna look into it now, but I'm currently not too sure about changing the default recovery set.

**Comment by NotAFlyingGoose** [comment]
I found the same issue with functions calls `foo(;`, struct definitions `struct {;`, and struct literals `Foo {;`

I've fixed a lot of it by not only checking for eof, but also for the default recovery set in several places

**Comment by NotAFlyingGoose** [comment]
I also added tests in `crates/parser/src/tests`
