### ISSUE TITLE
infinite recursion when inferring recursive types

### ISSUE THREAD

**Issue by lenawanel** [capy-language/capy#5]
```capy
Recursive :: struct {
    field: Recursive,
};

a := Recursive { }
```
will cause a stack-overflow.

**Comment by lenawanel** [comment]
this also happens if you add indirection by doing sth like:
```capy
Recursive :: struct {
    field: ^Recursive,
};

a := Recursive { field: 0 }
```
this only happens when constructing the type,
```capy
Recursive :: struct {
    field: ^Recursive,
};
```
and even it's counterpart without the `^ ` get compiled without errors, even though it should be impossible to compile.

**Comment by lenawanel** [comment]
@NotAFlyingGoose if you didn't already know, vectors can cause the same issue:

```
Vector3::distinct[3] Vector3;

a : Vector3 =  [] {};
```

**Comment by NotAFlyingGoose** [comment]
Oh wow! I was just about to commit a fix lol

I'll work on it but I'm not going to be available all day

**Comment by NotAFlyingGoose** [comment]
Now, the fix still won't allow types containing recursive indirection
```
Recursive :: struct {
    field: ^Recursive,
};
// doesn't compile
```
But as currently all pointers are supposed to be non-null, this isn't too much of an issue
