### ISSUE TITLE
weird behavior in `ptrs.capy` example

### ISSUE THREAD

**Issue by lenawanel** [capy-language/capy#9]
the `gen_ptr` function returns a pointer into it's local stack frame, so there are all sorts of weird behaviors which can happen. 
one example would be adding the `do_nothing` function and calling it after directly `gen_ptr` in main.

```capy
do_nothing :: () -> void {
    y := 1;
}
```
this will change the printed value from 42 to 1.

**Comment by NotAFlyingGoose** [comment]
Yeah I think I did that for fun but I never got around to changing it.

I'm going to remove the file since there are several other existing files that demonstrate pointers much better.
